/**
 * One-time script to fetch ALL product images from jonesproperties.biz Shopify store.
 * Reads the current property-images.ts, hits each product's JSON endpoint,
 * and writes a new version with images[] arrays.
 *
 * Usage: node scripts/fetch-images.mjs
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_FILE = resolve(__dirname, "../src/data/property-images.ts");

// Parse the existing TS file to extract property entries
function parseExistingEntries(source) {
  const entries = [];
  // Match each object literal in the array
  const objectRegex = /\{\s*name:\s*"([^"]*)",\s*address:\s*"([^"]*)",\s*image:\s*"([^"]*)",\s*type:\s*"([^"]*)",\s*shopifyUrl:\s*"([^"]*)"\s*\}/g;
  let match;
  while ((match = objectRegex.exec(source)) !== null) {
    entries.push({
      name: match[1],
      address: match[2],
      currentImage: match[3],
      type: match[4],
      shopifyUrl: match[5],
    });
  }
  return entries;
}

// Extract slug from shopifyUrl
function getSlug(shopifyUrl) {
  const parts = shopifyUrl.split("/products/");
  return parts[1] || null;
}

// Fetch all images for a product from Shopify JSON API
async function fetchProductImages(shopifyUrl) {
  const slug = getSlug(shopifyUrl);
  if (!slug) return [];

  const jsonUrl = `https://jonesproperties.biz/products/${slug}.json`;
  try {
    const response = await fetch(jsonUrl);
    if (!response.ok) {
      console.error(`  HTTP ${response.status} for ${slug}`);
      return [];
    }
    const data = await response.json();
    if (data.product && Array.isArray(data.product.images)) {
      return data.product.images.map((img) => img.src).filter(Boolean);
    }
    return [];
  } catch (err) {
    console.error(`  Error fetching ${slug}: ${err.message}`);
    return [];
  }
}

// Generate the new TypeScript file content
function generateTS(entries) {
  let out = `// Property images scraped from jonesproperties.biz
// Maps addresses to Shopify CDN image URLs
// Auto-generated by scripts/fetch-images.mjs

export interface PropertyImageEntry {
  name: string;
  address: string;
  images: string[];
  type: "apartment" | "house" | "commercial";
  shopifyUrl: string;
}

export const propertyImages: PropertyImageEntry[] = [\n`;

  let currentType = null;
  for (const entry of entries) {
    if (entry.type !== currentType) {
      currentType = entry.type;
      out += `  // === ${currentType.toUpperCase()}S ===\n`;
    }
    const imagesStr = entry.images.map((url) => `"${url}"`).join(", ");
    out += `  { name: "${escapeStr(entry.name)}", address: "${escapeStr(entry.address)}", images: [${imagesStr}], type: "${entry.type}", shopifyUrl: "${entry.shopifyUrl}" },\n`;
  }

  out += `];\n`;
  return out;
}

function escapeStr(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Main
async function main() {
  const source = readFileSync(DATA_FILE, "utf-8");
  const entries = parseExistingEntries(source);
  console.log(`Found ${entries.length} properties in property-images.ts`);

  const results = [];
  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    const slug = getSlug(entry.shopifyUrl);
    process.stdout.write(`[${i + 1}/${entries.length}] ${entry.name} (${slug})... `);

    const images = await fetchProductImages(entry.shopifyUrl);
    console.log(`${images.length} images`);

    results.push({
      name: entry.name,
      address: entry.address,
      images: images.length > 0 ? images : (entry.currentImage ? [entry.currentImage] : []),
      type: entry.type,
      shopifyUrl: entry.shopifyUrl,
    });

    // Small delay to be polite to the server
    if (i < entries.length - 1) {
      await new Promise((r) => setTimeout(r, 200));
    }
  }

  const tsContent = generateTS(results);
  writeFileSync(DATA_FILE, tsContent, "utf-8");
  console.log(`\nWrote updated property-images.ts with ${results.length} entries`);

  // Summary
  const totalImages = results.reduce((sum, r) => sum + r.images.length, 0);
  const multiImageCount = results.filter((r) => r.images.length > 1).length;
  console.log(`Total images: ${totalImages} across ${results.length} properties`);
  console.log(`Properties with multiple images: ${multiImageCount}`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
